name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        python-version: [3.7, 3.8, 3.9, '3.10', '3.11']

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        pip install --pre pymsbuild Cython
        pip install pytest

    - name: Build in place
      run: python -m pymsbuild

    - name: Test with pytest
      run: |
        python -m pymsbuild -c _msbuild_test.py
        pytest
      env:
        PYTHONPATH: src
